spring:
  cloud:
    gateway:
      routes:
        # http://localhost:8080/?to=qq
        - id: to_qq
          uri: http://qq.com
          predicates:
            - Query=to, qq
        # http://localhost:8080/?to=baidu
        - id: to_baidu
          uri: http://baidu.com
          predicates:
            - Query=to, baidu